### ISSUE TITLE
你好， 我想请教一个关于架构设计上的问题

### ISSUE THREAD

**Issue by sursir** [greengerong/greengerong.github.com#1]
我的项目为PHP项目。
我在项目中用到了领域模型。 去掉了服务层。
架构为 view -> control -> logic -> data

其中在 control -> logic 过度的时候有个问题。
因为在业务中用到了较多的参数，依赖了很多用户输入数据。
所以在传递这些数据的时候出现纠结了。

本着尽量少开放接口的原则 我想知开放一个调用接口，然后只通过此接口传递数据。
 这样出现一个问题:
1. 要么参数列表过长
2. 用键值对 又会造成接口参数不透明

自己拿不定主意。因为在这方面理解不够深。 又是初学者。 所以特来寻求帮助。
希望可以指点一二 : )

**Comment by greengerong** [comment]
对于参数过多，应该考虑简历一个request对象，这是数据传输对象，负责从领域对象到view的传输对象，有时它也可以是View的Object
